Feature/venue testcases
SOHO-Development-Team/BookingApplication pull request #27
Opened 2022-01-06 07:22 UTC by Backiaraj07

Page load issue and update modification done in
Room,
Venue,
Ratecard,
Hotels,
Menus.
And added Taskdefinition file for AWS Auto deployment

2022-01-06 09:06 UTC, sathish199308 commented on BookingSystem.BAL/Interface/IRateCardService.cs
> +        Task<RateCardsVM> GetRateCardDetailsByID(int? _ratecardid);
Hi Kindly not use _ in the prefix of the input parameters . Make it as a input parameters as RateCardID or rateCardId, kindly not use ratecardid

2022-01-06 09:06 UTC, sathish199308 commented on BookingSystem.BAL/Interface/IRateCardService.cs
>          Task<RateCardsVM> SaveRateCardDetails(RateCardsVM _ratecard);
Hi Kindly not use _ in the prefix of the input parameters

2022-01-06 09:07 UTC, sathish199308 commented on BookingSystem.BAL/Interface/IRoomService.cs
> +        Task<RoomsVM> GetRoomDetailsByID(int? _roomid);
Hi Kindly not use _ in the prefix of the input parameters . Make it as a input parameters as RoomID or roomId, kindly not use roomid

2022-01-06 09:07 UTC, sathish199308 commented on BookingSystem.BAL/Interface/IRoomService.cs
>          Task<RoomsVM> SaveRoomDetails(RoomsVM _room);
Hi Kindly not use _ in the prefix of the input parameters .

2022-01-06 09:10 UTC, vivekr2021 commented on BookingSystem.BAL/Interface/IRateCardService.cs
> +        Task<RateCardsVM> GetRateCardDetailsByID(int? _ratecardid);
Please practice adding Async as the suffix for Async methods
Instead "GetRateCardDetailsByID" use "GetRateCardDetailsByIDAsync"

2022-01-06 09:12 UTC, vivekr2021 requested changes

2022-01-06 09:12 UTC, vivekr2021 commented on BookingSystem.BAL/Interface/IHotelService.cs
> +        Task<HotelVM> GetHotelDetailsByID(int? HotelID);
Use Async in the suffix for Async methods
Use "GetHotelDetailsByIDAsync" Instead "GetHotelDetailsByID"

2022-01-06 09:15 UTC, manic1990 commented on BookingSystem.BAL/Service/VenueService.cs
> -               await _venueRepository.UpdateVenue(_venue);
Use ConfigureAwait(false) both method

2022-01-06 09:16 UTC, manic1990 commented on BookingSystem.BAL/Service/VenueService.cs
>                  var venues = await _venueRepository.saveVenue(_venue);
Use ConfigureAwait(false).

2022-01-06 09:23 UTC, manic1990 commented on BookingSystem.BAL/Interface/IHotelService.cs
>          bool UpdateHotelDetails(HotelVM _Hotel);
Use Task<bool >

2022-01-06 09:24 UTC, manic1990 commented on BookingSystem.BAL/Interface/IRateCardService.cs
>          bool UpdateRateCardDetails(RateCardsVM _ratecard);
Use Task for async method

2022-01-06 09:25 UTC, manic1990 commented on BookingSystem.BAL/Interface/IRoomService.cs
>          bool UpdateRoomDetails(RoomsVM _room);
Use Task for async method

2022-01-06 09:25 UTC, manic1990 commented on BookingSystem.BAL/Interface/IVenueService.cs
>          bool UpdateVenueDetails(VenuesVM _venue);
Use Task for async method

2022-01-06 12:51 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRateCardService.cs
> +        Task<RateCardsVM> GetRateCardDetailsByID(int? _ratecardid);
Sure sir. Changes done.

2022-01-06 12:51 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRateCardService.cs
>          Task<RateCardsVM> SaveRateCardDetails(RateCardsVM _ratecard);
Changes done

2022-01-06 12:51 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRoomService.cs
>          Task<RoomsVM> SaveRoomDetails(RoomsVM _room);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRoomService.cs
> +        Task<RoomsVM> GetRoomDetailsByID(int? _roomid);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IHotelService.cs
> +        Task<HotelVM> GetHotelDetailsByID(int? HotelID);
Sure sir.

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Service/VenueService.cs
> -               await _venueRepository.UpdateVenue(_venue);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IHotelService.cs
>          bool UpdateHotelDetails(HotelVM _Hotel);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRateCardService.cs
>          bool UpdateRateCardDetails(RateCardsVM _ratecard);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IRoomService.cs
>          bool UpdateRoomDetails(RoomsVM _room);
Changes done

2022-01-06 12:52 UTC, Backiaraj07 commented on BookingSystem.BAL/Interface/IVenueService.cs
>          bool UpdateVenueDetails(VenuesVM _venue);
Changes done

2022-01-07 08:32 UTC, sathish199308 approved these changes
Approved the PR

2022-01-07 08:33 UTC, merged