Feature/room test cases
SOHO-Development-Team/BookingApplication pull request #28
Opened 2022-01-06 09:54 UTC by sathish199308

Room Test Case for API Client and MVC

2022-01-06 10:03 UTC, vivekr2021 requested changes

2022-01-06 10:03 UTC, vivekr2021 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientSaveRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Please don't hard-code the URL

2022-01-06 10:03 UTC, vivekr2021 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientSaveRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Please don't hard-code the URL

2022-01-06 10:03 UTC, vivekr2021 commented on BookingSystem.Tests/Integration.Tests/RoomRepositoryTest/GetRoomTest.cs
> +            var options = new DbContextOptionsBuilder<DataContext>().UseInMemoryDatabase(databaseName: "BookingSystem").Options;
Why do we use the DB Name hard-coded? 
What will happen if the application connected with some other DB?

2022-01-07 05:42 UTC, sathish199308 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientGetRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Hi Sir, I remove the hard Coded Value get the values from appunittestsetting.json file

2022-01-07 05:42 UTC, sathish199308 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientGetRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Hi Sir, I remove the hard Coded Value get the values from appunittestsetting.json file

2022-01-07 05:42 UTC, sathish199308 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientSaveRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Hi Sir, I remove the hard Coded Value get the values from appunittestsetting.json file

2022-01-07 05:42 UTC, sathish199308 commented on BookingSystem.Tests/ApiClient.Tests/Room/APIClientSaveRoomTest.cs
> +            httpClient.BaseAddress = new Uri("https://localhost:44348/api/");
Hi Sir, I remove the hard Coded Value get the values from appunittestsetting.json file

2022-01-07 05:43 UTC, sathish199308 commented on BookingSystem.Tests/Integration.Tests/RoomRepositoryTest/GetRoomTest.cs
> +            var options = new DbContextOptionsBuilder<DataContext>().UseInMemoryDatabase(databaseName: "BookingSystem").Options;
Hi Sir, DB Name I just put as a mock up values, now I changed it will be dynamically push from the Json file.

2022-01-07 08:54 UTC, Backiaraj07 approved these changes
Comments verified

2022-01-07 08:55 UTC, Backiaraj07 approved these changes
Comments resolved

2022-01-07 08:56 UTC, merged