Feature/UI design
SOHO-Development-Team/BookingApplication pull request #61
Opened 2022-02-14 07:02 UTC by sathish199308

2022-02-14 07:32 UTC, bhairab15 requested changes

2022-02-14 07:32 UTC, bhairab15 commented on BookingSystem/Views/Dashboard/DashboardView.cshtml
> +                            @Html.DropDownList("status", new List<SelectListItem> { new SelectListItem { Text = "Status", Value = "Status" },
Why are we making hard coded item, can we use enum ?

2022-02-14 07:32 UTC, bhairab15 commented on BookingSystem/Controllers/DashboardController.cs
> +                    if (status == "All")
Please use enum

2022-02-14 07:32 UTC, bhairab15 commented on BookingSystem/Controllers/DashboardController.cs
>              _logger.LogInformation(nameof(BookingDashboardController) + "." + nameof(DashboardView) + Constant.start);
Please use String interpolation

2022-02-15 06:45 UTC, merged

2022-02-15 06:45 UTC, Backiaraj07 commented
Comments resolved